#+PROPERTY: header-args :results silent :tangle yes

* Some defaults

** general
   #+BEGIN_SRC emacs-lisp
(menu-bar-mode 1) ;; show menu: useful things there some times!
(tool-bar-mode 0) ;; toolbar definetly not
(scroll-bar-mode 0) ;; hide system scrollbars

;; CUA
(cua-mode 0) ;; ctrl-c ctrl-v copy paste etc
(global-set-key (kbd "C-v") 'yank)

(global-hl-line-mode 1) ;; Highlight current line
(fset 'yes-or-no-p 'y-or-n-p)
;;(define-key cua-global-keymap [C-return] nil) ;; don't remember the use-case of this
;;(define-key cua--cua-keys-keymap [C-z] nil)
(global-visual-line-mode 1) ;; word/line wrap
(winner-mode t) ;; C-c left will undo window position changes
(setq ring-bell-function 'ignore)
(global-display-line-numbers-mode 1)
(setq inhibit-startup-screen 1)
(delete-selection-mode 1) ;; delete selected region if starting typing

;; Keeping clipboard data before replacing it with emacs copy/kill etc
(setq save-interprogram-paste-before-kill t)

;; fixing fucking encoding things?
(prefer-coding-system 'utf-8)

(put 'narrow-to-region 'disabled nil)
   #+END_SRC

** functions
   #+BEGIN_SRC emacs-lisp
(defun indent-buffer ()
  (interactive)
  (save-excursion
    (indent-region (point-min) (point-max) nil)))

(defun toggle-comment-on-line ()
  "comment or uncomment current line"
  (interactive)
  (comment-or-uncomment-region (line-beginning-position) (line-end-position))
  )
   #+END_SRC
** bindings
   #+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-/") 'toggle-comment-on-line)
(global-set-key (kbd "C-?") 'comment-or-uncomment-region)

(global-set-key (kbd "M-n") 'outline-next-visible-heading)
(global-set-key (kbd "M-p") 'outline-previous-visible-heading)
   #+END_SRC
** backups
   - https://stackoverflow.com/questions/151945/how-do-i-control-how-emacs-makes-backup-files
   - https://www.emacswiki.org/emacs/BackupDirectory

   apparently the folder name needs a trailing slash, if not emacs continued to loitter the file directory (see https://emacs.stackexchange.com/questions/17210/how-to-place-all-auto-save-files-in-a-directory)
   
   #+BEGIN_SRC emacs-lisp
(defvar --backup-directory (concat user-emacs-directory "backups/"))
(if (not (file-exists-p --backup-directory))
    (make-directory --backup-directory t))
(setq backup-directory-alist `((".*" . ,--backup-directory)))

(setq auto-save-file-name-transforms
          `((".*" ,--backup-directory t)))

(setq make-backup-files t               ; backup of a file the first time it is saved.
      backup-by-copying t               ; don't clobber symlinks
      version-control t                 ; version numbers for backup files
      delete-old-versions t             ; delete excess backup files silently
      delete-by-moving-to-trash t
      kept-old-versions 6               ; oldest versions to keep when a new numbered backup is made (default: 2)
      kept-new-versions 9               ; newest versions to keep when a new numbered backup is made (default: 2)
      auto-save-default t               ; auto-save every buffer that visits a file
      auto-save-timeout 20              ; number of seconds idle time before auto-save (default: 30)
      auto-save-interval 200            ; number of keystrokes between auto-saves (default: 300)
      )   
   #+END_SRC
* Package source, use-package etc
  #+BEGIN_SRC emacs-lisp
(setq package-enable-at-startup nil)

(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")
			 ("org" . "https://orgmode.org/elpa/")))
  #+END_SRC

** use-package
   Bootstrapping use-package
   #+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(setq use-package-always-ensure t)
(setq use-package-always-defer t)
(setq use-package-verbose 'verbose)
   #+END_SRC

** straight.el
   see
   + https://github.crookster.org/switching-to-straight.el-from-emacs-26-builtin-package.el/
   + https://github.com/raxod502/straight.el/blob/develop/README.md#getting-started

   #+BEGIN_SRC emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
	(url-retrieve-synchronously
	 "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	 'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq straight-vc-git-default-clone-depth 1)
;; (setq straight-use-package-by-default t)
   #+END_SRC
** Custom directories
   Note: in [[file:init.el]] we defined the =relative-from-init= function.
   Here we add relative folders (from the init file) to load files from.
   + [ ] TODO add here something like a =custom= folder (which will be in gitignore)
   #+BEGIN_SRC emacs-lisp
(add-to-list 'load-path (relative-from-init "elisp"))
   #+END_SRC

* Org customizations
** Src block customizations
   #+BEGIN_SRC emacs-lisp
(setq org-src-preserve-indentation t)
   #+END_SRC
** Log, scheduling etc
   #+BEGIN_SRC emacs-lisp
(setq org-log-note-clock-out t)
   #+END_SRC
** Images customizations
   #+BEGIN_SRC emacs-lisp
(with-eval-after-load 'org
  (setq org-image-actual-width 400))
   #+END_SRC
** habits
   #+BEGIN_SRC emacs-lisp
(with-eval-after-load 'org
  (add-to-list 'org-modules 'org-habit t))
   #+END_SRC 

   And add org-file to the list of agenda files.
   =(org-agenda-file-to-front)=
   see
   + https://orgmode.org/manual/Tracking-your-habits.html
   + https://www.youtube.com/watch?v=acj3NhXlnnk

   useful command
   + org-agenda-file-to-front
   + (setq org-log-done 'time)
** babel languages
   #+BEGIN_SRC emacs-lisp
(with-eval-after-load 'org
  (org-babel-do-load-languages 'org-babel-load-languages
			       '(
				 (shell . t)
				 (scheme . t)
				 ;;	  (python . t)
				 ;;	  (sql . t)
				 ;;	  (python . t)
				 ;;	  (restclient . t)
				 ;;	  (php . t)
				 ;;	  (clojure . t)
				 )
			       ))
   #+END_SRC

** org-babel-eval-in-repl
   #+BEGIN_SRC emacs-lisp
(use-package eval-in-repl
  ;; :ensure t
  ;; uhm.. use-package fail? i have default ensure set to true,
  ;; yet without the custom :ensure t it didn't work
  )


(use-package org-babel-eval-in-repl
  ;; For the C-return command to work, we either have to "demand" or
  ;; require the package after org is loaded
  :init
  (with-eval-after-load 'org
    (require 'org-babel-eval-in-repl))
  :commands (ober-eval-in-repl)
  :bind
  (:map org-mode-map
	("C-<return>" . ober-eval-in-repl)))
   #+END_SRC

** exporting to html
   #+BEGIN_SRC emacs-lisp
(use-package htmlize)
   #+END_SRC
** wrap blocks of text
   http://pragmaticemacs.com/emacs/wrap-text-in-an-org-mode-block/
   - [X] indent properly the inserted text
     - (indent-for-tab-command)
     - (newline-and-indent)
     - (indent-new-comment-line)
   
   #+BEGIN_SRC emacs-lisp
(defun aod.org/wrap-region ()
  "Make a template at point."
  (interactive)
  (if (org-at-table-p)
      (call-interactively 'org-table-rotate-recalc-marks)
    (let* ((choices '(("s" . "SRC")
                      ("e" . "EXAMPLE")
                      ("q" . "QUOTE")
                      ("v" . "VERSE")
                      ("c" . "CENTER")
		      ("C" . "COMMENT")
                      ("l" . "LaTeX")
                      ("h" . "HTML")
                      ("a" . "ASCII")))
           (key
            (key-description
             (vector
              (read-key
               (concat (propertize "Template type: " 'face 'minibuffer-prompt)
                       (mapconcat (lambda (choice)
                                    (concat (propertize (car choice) 'face 'font-lock-type-face)
                                            ": "
                                            (cdr choice)))
                                  choices
                                  ", ")))))))
      (let ((result (assoc key choices)))
        (when result
          (let ((choice (cdr result)))
            (cond
             ((region-active-p)
              (let ((start (region-beginning))
                    (end (region-end)))
                (goto-char end)
		(newline-and-indent)
                (insert "#+END_" choice)
		(newline-and-indent)
                (goto-char start)
		;; (newline)
		
		(previous-line)
		(indent-new-comment-line)
                (insert "#+BEGIN_" choice)
		))
             (t
	      (indent-new-comment-line)
              (insert "#+BEGIN_" choice)
	      (newline-and-indent)
              (save-excursion
		(newline-and-indent)
		(insert "#+END_" choice))
	      (indent-for-tab-command)
	      ))))))))

   #+END_SRC
** new moon calendar
   #+BEGIN_SRC emacs-lisp
(load-file (relative-from-init "elisp/aod-new-moon.el"))   
   #+END_SRC
** opening links
   #+BEGIN_SRC emacs-lisp
(setq browse-url-browser-function 'aod.web/browse-function)
(setq aod.web/browse-private-p nil)

(defun aod.web/toggle-browse-private ()
  (interactive)
  (setq aod.web/browse-private-p (not aod.web/browse-private-p))
  (message "openining in private? %s" aod.web/browse-private-p))

(defun aod.web/browse-function (url &rest ignore)
  "Browse URLs in either normal mode or in a firefox private window"
  ;; (interactive "sURL: ")
  (if aod.web/browse-private-p
      (progn
	(message "opening in private firefox window")
	(shell-command (concat "firefox --private-window " url)))
    (progn
      (message "openining in normal browser window")
      (browse-url-default-browser url))
    ))   
   #+END_SRC
* Helm
  #+BEGIN_SRC emacs-lisp
(use-package helm
  :bind(
	("M-x" . helm-M-x)
	("C-<tab>" . helm-mini)
	("C-x C-f" . helm-find-files)
	("C-S-v" . helm-show-kill-ring)
	:map helm-map
	("<tab>" . helm-execute-persistent-action)
	("<left>" . left-char)
	("<right>" . right-char)
	:map helm-find-files-map ;; to be able to select/copy filenames
	("<left>" . left-char)
	("<right>" . right-char)
	("C-SPC" . set-mark-command)
	)
  :config
  (setq helm-M-x-fuzzy-match t
	helm-recentf-fuzzy-match t
	helm-apropos-fuzzy-match t
	helm-buffers-fuzzy-matching t
	helm-completion-in-region-fuzzy-match t
	helm-mode-fuzzy-match t)
  
  (setq helm-swoop-pre-input-function
	(lambda ()
	  ;; the default: thing-at-point
	  ;;(thing-at-point 'symbol)
	  (if mark-active
	      (buffer-substring-no-properties (region-beginning) (region-end))
	    nil)
	  ))
  
  (helm-mode 1)
  )

(use-package helm-swoop
  :config
  (setq helm-swoop-use-fuzzy-match nil)
  (setq helm-swoop-speed-or-color t)
  (setq helm-autoresize-max-height 35)
  (setq helm-autoresize-min-height 20)
  (setq helm-autoresize-mode 1)
  )

(use-package helm-ag)

  #+END_SRC

** installing ag (used in helm-ag)
   In ubuntu:
   #+BEGIN_SRC sh
sudo apt-get install silversearcher-ag
   #+END_SRC
* Window management
** Resizing (windresize)
   #+BEGIN_SRC emacs-lisp
(use-package windresize
  :config
  (setq windresize-default-increment 5)
  )
   #+END_SRC

** ace-window
   #+BEGIN_SRC emacs-lisp
(use-package ace-window
  :bind (("M-o" . ace-window))
  :config
  (setq-default aw-scope 'frame) ; switching windows only i current frame
  )
   #+END_SRC

* Project management
** Projectile & neotree
   Useful neotree shortcuts
   + =A= : stretch toggle
   + =U= : go up to parent
   + =C-c C-a= : collapse all
     + [ ] set <S-tab> for collapse all?

   #+BEGIN_SRC emacs-lisp
(use-package projectile
  :demand t
  :config
  (projectile-mode 1)
  ;; speed!
  (setq projectile-indexing-method 'hybrid)
  (setq projectile-completion-system 'helm)
  ;; https://github.com/bbatsov/projectile/issues/1302#issuecomment-433894379
  ;; windows fix
  ;; (setq projectile-git-submodule-command nil)
  ;; oor install tr with "choco install tr"
  ;; oor msys2 paths (see heading)
  )
(use-package helm-projectile
  :commands (helm-projectile-find-file
	     helm-projectile-ag)
  )

(defun display-line-numbers-disable-hook (_)
  "Disable display-line-numbers locally."
  (display-line-numbers-mode -1))

(use-package neotree
  :config
  (setq neo-smart-open t)
  (add-hook 'neo-after-create-hook 'display-line-numbers-disable-hook)
  :bind(
	("<f8>" . neotree-toggle)
	)
  )
   #+END_SRC
* Buffer management
** ibuffer : grouping by project
   #+BEGIN_SRC emacs-lisp
(use-package ibuffer-projectile
  :ensure t
  :hook
  (ibuffer .
	   (lambda ()
	     (ibuffer-projectile-set-filter-groups)
	     (unless (eq ibuffer-sorting-mode 'alphabetic)
	       (ibuffer-do-sort-by-alphabetic))))
  )
   #+END_SRC
* Appearance
** Cursor
   #+BEGIN_SRC emacs-lisp
(blink-cursor-mode t)
(setq-default cursor-type 'box)
   #+END_SRC
** Welcome screen
   #+BEGIN_SRC emacs-lisp
(use-package dashboard
  :demand t
  :diminish dashboard-mode
  :config
  ;;  (setq dashboard-banner-logo-title "your custom text")
  (setq dashboard-startup-banner 1) ;; integer is for text
  (setq dashboard-items '(
			  (projects . 10)
                          (bookmarks . 10)
			  (recents  . 10)
			  ))
  (dashboard-setup-startup-hook)
  ;; fixing emacs client starting with scratch
  ;; https://www.reddit.com/r/emacs/comments/8i2ip7/emacs_dashboard_emacsclient/
  (if (= 1 (length command-line-args))
      ;; going to dashboard only if we didn't pass a file
      (setq initial-buffer-choice (lambda () (get-buffer "*dashboard*"))))
  )
   #+END_SRC
** frame title
   For distinguishing between windows and linux (WSL in windows)
   #+BEGIN_SRC emacs-lisp
;; note: can't use for some reason directy the system-type
(setq system-type-name (symbol-name system-type))
(setq frame-title-format '("%f  -- " system-type-name))
(defun aod/name-frame (name)
  (interactive "Mname:")
  (setq frame-title-format `(,name " -- %f  -- " system-type-name))
  )
   #+END_SRC
** COMMENT monokai
   #+BEGIN_SRC emacs-lisp
(use-package monokai-theme)
  

;; (use-package sublime-themes
;;   
;;   :config
;;   (load-theme 'spolsky t)
;;   )
   #+END_SRC
** doom
   #+BEGIN_SRC emacs-lisp
(use-package doom-themes
  :demand t
  :config
  (load-theme 'doom-molokai t)
  (doom-themes-visual-bell-config)
  (doom-themes-neotree-config)
  ;; https://github.com/domtronn/all-the-icons.el/issues/28#issuecomment-312089198
  (setq inhibit-compacting-font-caches t)
  (setq doom-themes-neotree-file-icons t)
  )
   #+END_SRC
** doom-modeline
   #+BEGIN_SRC emacs-lisp
(use-package doom-modeline
   :hook (after-init . doom-modeline-mode))
   #+END_SRC

   + [ ] TODO
     If sometimes you don't see the icons (it happens on doom-modeline reset and enable again)
   #+BEGIN_SRC emacs-lisp :tangle no
;; (setq doom-modeline-icon (display-graphic-p))
(setq doom-modeline-buffer-state-icon t)
   #+END_SRC

   Note: after you have to run =all-the-icons-install-fonts= with M-x.
*** minions: showing minor modes
    https://github.com/tarsius/minions
    A minor-mode menu for the mode line

    #+BEGIN_SRC emacs-lisp
(use-package minions
  :demand t
  :config
  (minions-mode 1)
  (setq doom-modeline-minor-modes (featurep 'minions)))
    #+END_SRC
** COMMENT powerline
   #+BEGIN_SRC emacs-lisp
(use-package powerline
  :config
  (powerline-default-theme))
   #+END_SRC

** highlighting matching tag (show-paren)
   #+BEGIN_SRC emacs-lisp
(use-package paren
  :hook (prog-mode . show-paren-mode)
  :init
  (set-face-attribute 'show-paren-match nil
		      :box '(:line-width -1 :color "#ccc")
		      :foreground nil
		      :weight 'normal))
   #+END_SRC
* editing etc
** linear ranges (tiny)
   #+BEGIN_SRC emacs-lisp
(use-package tiny)
   #+END_SRC
** auto completion
   #+BEGIN_SRC emacs-lisp
(use-package company
  :hook (after-init . global-company-mode)
  :config
  (setq company-dabbrev-downcase nil)
  (setq company-dabbrev-ignore-case t))
   #+END_SRC

** Hiding/showing blocks
   + [[file:emacs-lisp/hideshowvis.el]]
     adds clickable + - icons in the left fringe for folding/unfolding (hiding/showing) code blocks
   + [[file:emacs-lisp/hideshow-org.el]]
     adds functionality similar to org-mode: toggle code block hide/show by pressing tab
   #+BEGIN_SRC emacs-lisp
(use-package hideshow-org
  ;; https://github.com/shanecelis/hideshow-org
  :load-path "elisp/"
  :hook (prog-mode . hs-org/minor-mode))

(use-package hideshowvis
  ;; https://www.emacswiki.org/emacs/hideshowvis.el
  :load-path "elisp/"
  :hook (prog-mode . hideshowvis-minor-mode))
   #+END_SRC

** selection
   #+BEGIN_SRC emacs-lisp
;; usecase: select the block (enclosed by parenthesis).. expand -> wrap around the outter block
(use-package expand-region)

(use-package multiple-cursors
  :bind (("C->" . mc/mark-next-like-this-word)
	 ("C-<" . mc/mark-previous-like-this-word)
	 ( "M-<f3>" . mc/mark-all-like-this) ;; submlime like
	 ("C-S-<mouse-1>" . mc/add-cursor-on-click))
  )
   #+END_SRC
** undo
   #+BEGIN_SRC emacs-lisp
(use-package undo-tree
  :config
  (global-undo-tree-mode 1)
  (unbind-key "C-/" undo-tree-map)
  (unbind-key "C-?" undo-tree-map)
  :bind(
	("M-/" . undo-tree-visualize)
	("C-z" . undo-tree-undo)
	("C-S-z" . undo-tree-redo)
	)
  )
   #+END_SRC
** Working with lisps
*** paredit
    #+BEGIN_SRC emacs-lisp
(use-package paredit
  ;; <C-right>	paredit-forward-slurp-sexp
  ;; <C-left>	paredit-forward-barf-sexp
  ;; <C-M-right>	paredit-backward-barf-sexp
  ;; <C-M-left>	paredit-backward-slurp-sexp  :config
  :hook ((clojure-mode emacs-lisp-mode scheme-mode ) . paredit-mode)
  :config
  (unbind-key "C-<right>" paredit-mode-map)
  (unbind-key "C-<left>" paredit-mode-map)
  :bind(:map paredit-mode-map
	("M-]" . paredit-forward-slurp-sexp) ;; c ->
	("M-[" . paredit-forward-barf-sexp) ;; c <-
	("M-}" . paredit-backward-barf-sexp) ;; C-M >
	("M-{" . paredit-backward-slurp-sexp) ;; C M <
	))
    #+END_SRC
    Useful tricks
    + swapping parens to brackets etc
      https://stackoverflow.com/a/24784563/8720686
*** COMMENT parinfer
    #+BEGIN_SRC emacs-lisp
(defun add-parinfer-hooks ()
  (add-hook 'clojure-mode-hook #'parinfer-mode)
  (add-hook 'emacs-lisp-mode-hook #'parinfer-mode)
  (add-hook 'common-lisp-mode-hook #'parinfer-mode)
  (add-hook 'scheme-mode-hook #'parinfer-mode)
  (add-hook 'lisp-mode-hook #'parinfer-mode))

(use-package parinfer
  :bind
  (("C-," . parinfer-toggle-mode))
  :init
  (progn
    (setq parinfer-extensions
          '(
	    defaults       ; should be included.
            ;; pretty-parens  ; different paren styles for different modes.
            ;; evil           ; If you use Evil.
            ;; lispy          ; If you use Lispy. With this extension, you should install Lispy and do not enable lispy-mode directly.
            
paredit        ; Introduce some paredit commands.
            smart-tab      ; C-b & C-f jump positions and smart shift with tab & S-tab.
            smart-yank
	    ))   ; Yank behavior depend on mode.
    ))
    #+END_SRC
*** aggresive indent?
    https://github.com/Malabarba/aggressive-indent-mode
    vs electric
    #+BEGIN_SRC emacs-lisp
(use-package aggressive-indent
  :hook ((clojure-mode emacs-lisp-mode) . aggressive-indent-mode)
  )
    #+END_SRC
** jumping around (ace jump)

   #+BEGIN_SRC emacs-lisp
(use-package ace-jump-mode
  :config
  (setq-default ace-jump-mode-scope 'frame) ; jumping only in current frame
  )
   #+END_SRC
** Rainbow
   Rainbow-mode is for previewing hex color strings in any buffer! :)
   had problems around <2020-05-07 Thu> . the .el file was.. empty??
   #+BEGIN_SRC emacs-lisp
(use-package rainbow-mode)
   #+END_SRC

   Rainbow-delimiters are here to save the day for lisps! (and not only)
   Highlighting matching pairs with different colors
   #+BEGIN_SRC emacs-lisp
;; cause in the default colors there was some white cursors, not really apparent
'(((((((((())))))))))

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode)
  :config
  ;; (my-rainbow-custom-colors)
  (set-face-attribute 'rainbow-delimiters-depth-1-face nil
		      :foreground "#e91e63")
  (set-face-attribute 'rainbow-delimiters-depth-2-face nil
		      :foreground "#2196F3")
  (set-face-attribute 'rainbow-delimiters-depth-3-face nil
		      :foreground "#EF6C00")
  (set-face-attribute 'rainbow-delimiters-depth-4-face nil
		      :foreground "#B388FF")
  (set-face-attribute 'rainbow-delimiters-depth-5-face nil
		      :foreground "#76ff03")
  (set-face-attribute 'rainbow-delimiters-depth-6-face nil
		      :foreground "#26A69A")
  (set-face-attribute 'rainbow-delimiters-depth-7-face nil
		      :foreground "#FFCDD2")
  (set-face-attribute 'rainbow-delimiters-depth-8-face nil
		      :foreground "#795548")
  (set-face-attribute 'rainbow-delimiters-depth-9-face nil
		      :foreground "#DCE775")
  )
   #+END_SRC

** LSP: Language Server Protocol
   #+BEGIN_SRC emacs-lisp
(use-package lsp-mode
  :commands lsp
  :config
  (add-to-list 'lsp-language-id-configuration '(clojure-mode . "clojure-mode"))
  :init
  (setq lsp-enable-indentation nil))

(use-package lsp-ui
  :commands lsp-ui-mode)

(use-package company-lsp
  :commands company-lsp)

   #+END_SRC
** Linting
   Flycheck: checking only when saving (not when editing the file - can cause slowness)
   #+BEGIN_SRC emacs-lisp
(use-package flycheck
  
  :config
  (setq flycheck-check-syntax-automatically '(save mode-enabled))
  )
   #+END_SRC
** HEX colors
   an alternative to rainbow-mode? 
   #+BEGIN_SRC emacs-lisp :tangle no
   (load-file (relative-from-init "elisp/xah.el"))
   #+END_SRC
   And now you can call the =xah-syntax-color-hex= function in any buffer :)
   Found at http://ergoemacs.org/emacs/xah-css-mode.html
** Writing - center text
   When writing a post, article or whatever, I don't want lines to extend all across the screen.
   
   credits: https://bzg.fr/en/emacs-strip-tease.html/
   
   #+BEGIN_SRC emacs-lisp
;; A small minor mode to use a big fringe
(defvar bzg-big-fringe-mode nil)
(define-minor-mode bzg-big-fringe-mode
  "Minor mode to use big fringe in the current buffer."
  :init-value nil
  :global t
  :variable bzg-big-fringe-mode
  :group 'editing-basics
  (if (not bzg-big-fringe-mode)
      (set-fringe-style nil)
    (set-fringe-mode
     (/ (- (frame-pixel-width)
           (* 100 (frame-char-width)))
        2))))

   #+END_SRC
** TODO Writing - spelling
   TBD
* (Ma)git
  #+BEGIN_SRC emacs-lisp
(use-package magit
  ;; show-all is meant for org-mode. ediff would show org-mode files folded
  :hook (ediff-prepare-buffer . show-all)
  :config
  (setq ediff-split-window-function 'split-window-horizontally)
  (setq ediff-window-setup-function 'ediff-setup-windows-plain)
  )
  #+END_SRC

  Ediff: great diff tool that can be used in magit :)
  Customizing colors cause in doom-molokai theme you could't notice anything
  #+BEGIN_SRC emacs-lisp
(use-package ediff
  :config
  ;; A head (last commit)
  (set-face-attribute 'ediff-current-diff-A nil
		      :background "#8b0000"
		      :foreground "#CCC")
  ;; B index (stage)
  (set-face-attribute 'ediff-current-diff-B nil
		      :background "#008b00"
		      :foreground "#CCC")
  ;; C working tree
  (set-face-attribute 'ediff-current-diff-C nil
		      :background "#8b5a00"
		      :foreground "#CCC")
  )
  #+END_SRC
* Languages
** Clojure
   #+BEGIN_SRC emacs-lisp
(use-package clojure-mode
  :bind(
	:map clojure-mode-map
	("C-<return>" . cider-eval-defun-at-point)
	("M-<return>" . cider-eval-last-sexp)
	)
  )
   #+END_SRC

*** repl (cider etc)
    Cider is amazing :)
    #+BEGIN_SRC emacs-lisp
(use-package cider)

(use-package clj-refactor
  ;; WIP
  :commands (clj-refactor-mode))
    #+END_SRC
*** Linting
    Note: have to install =clj-kondo= with =npm install -g clj-kondo=
    #+BEGIN_SRC emacs-lisp
(use-package flycheck-clj-kondo
  :init
  (with-eval-after-load 'flycheck
    (require 'flycheck-clj-kondo))
  )
    #+END_SRC

** Scheme
   #+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.sls\\'" . scheme-mode))   
   #+END_SRC

   Geiser fucking annoyes me. Asks everytime when I open an =ss= file for scheme implementation
   #+BEGIN_SRC emacs-lisp
(use-package geiser
  :config
  (setq geiser-chez-binary "scheme")
  (setq geiser-default-implementation 'chez)
  ;; need to reopen the file for that.. heh
  (setq geiser-implementations-alist '	
	(((regexp "\\.scm$") guile)
	 ((regexp "\\.ss$") chez)
	 ((regexp "\\.rkt$") racket)))
  ;;:init (add-hook 'scheme-mode-hook 'geiser-mode)
  ;; :bind(
  ;; 	:map geiser-mode-map
  ;; 	("C-<return>" . geiser-eval-defition)
  ;; 	("M-<return>" . geiser-eval-last-sexp)
  ;; 	)
  )
   #+END_SRC

   #+BEGIN_SRC emacs-lisp
(use-package cmuscheme
  :load-path "elisp/"
  :bind(
	:map scheme-mode-map
	("C-<return>" . scheme-send-definition)
	("M-<return>" . scheme-send-last-sexp)
	)
  )
   #+END_SRC
   
*** windows path
    #+BEGIN_SRC emacs-lisp :tangle (when (eq system-type 'windows-nt) "yes")
(add-to-list 'exec-path "c:/Program Files/Chez Scheme 9.5.2/bin/ta6nt/")
    #+END_SRC
** Rust
   #+BEGIN_SRC emacs-lisp
(use-package rust-mode)   
   #+END_SRC
** etc (yaml..)
   #+BEGIN_SRC emacs-lisp
(use-package yaml-mode)
   #+END_SRC
  
* Web
** restclient
   Associating with =.http= files
   #+BEGIN_SRC emacs-lisp
(use-package restclient
  :ensure t
  :mode ("\\.http\\'" . restclient-mode)
  )
   #+END_SRC

   Allowing restclient snippets in org-mode
   + [ ] how can i load this? 
   #+BEGIN_SRC emacs-lisp
(use-package ob-restclient
  :init ; init is ran before a package is loaded
  (with-eval-after-load 'org
    (require 'ob-restclient))
  :config
  (org-babel-do-load-languages 'org-babel-load-languages
			       '((restclient . t))))
   #+END_SRC
* Interface enhancmenets, key bindings
** Key-chord
   #+BEGIN_SRC emacs-lisp
(defun key-chord-helm ()
  ;; helm: , (right hand middle finger)
  (key-chord-define-global ",r" 'helm-all-mark-rings) ;; Rings
  (key-chord-define-global ",m" 'helm-mini) ;; Mini
  (key-chord-define-global ",s" 'helm-swoop) ;; Swoop
  (key-chord-define-global ",t" 'helm-projectile-find-file) ;; projecTile
  ;; helm-projectile-ag gives me bug in window, use projectile-ag? .. 
  (key-chord-define-global ",g" 'helm-projectile-ag) ;; aG
  )

(defun key-chord-ace-jump ()
  ;; ace: c (c for jump : left hand middle finger)
  (key-chord-define-global "cj" 'ace-jump-mode)
  ;; Jump Character
  (key-chord-define-global "ck" 'ace-jump-char-mode)
  ;; Jump Line
  (key-chord-define-global "cl" 'ace-jump-line-mode)
  )

(defun key-chord-windows-management ()
  ;; move between windows -WASD- like movement, except for the right hand
  ;; using ;
  (key-chord-define-global ";w" 'windmove-up)
  (key-chord-define-global ";a" 'windmove-left)
  (key-chord-define-global ";s" 'windmove-down)
  (key-chord-define-global ";d" 'windmove-right)

  ;; windows
  (key-chord-define-global ";q" 'delete-window) ;;q Quit
  (key-chord-define-global ";e" 'delete-other-windows)
  (key-chord-define-global ";f" (lambda () (interactive)(split-window-horizontally) (other-window 1))) ;; f home row
  (key-chord-define-global ";v" (lambda () (interactive)(split-window-vertically) (other-window 1))) ;; Vertical

  (key-chord-define-global ";r" 'windresize) ;; Resize
  )

(defun key-chord-editing ()
  ;; Expand Region (r for region)
  (key-chord-define-global "rj" 'er/expand-region)
  )

(use-package key-chord
  :demand t
  :config
  ;; disable in mini buffers
  (setq key-chord-two-keys-delay .05
	key-chord-one-key-delay .1)
  (defun disable-key-chord-mode ()
    (set (make-local-variable 'input-method-function) nil))

  (add-hook 'minibuffer-setup-hook #'disable-key-chord-mode)
  (key-chord-mode 1)

  (key-chord-helm)
  (key-chord-windows-management)
  (key-chord-editing)
  (key-chord-ace-jump)
  )
   #+END_SRC

** Which key
   https://github.com/justbur/emacs-which-key
   Get a feedback about the current key sequences, what can i press afterwards?
   #+BEGIN_SRC emacs-lisp
(use-package which-key
  :demand t
  :config
  (which-key-mode)
  (setq which-key-idle-delay 0.5) ;; default: 1
  )
   #+END_SRC

* Presentation? (command-log)
  #+BEGIN_SRC emacs-lisp
(use-package command-log-mode
  :commands global-command-log-mode)
  #+END_SRC
  Usage:
  - global-command-log-mode
  - clm/open-command-log-buffer
* Windows
  :PROPERTIES:
  :header-args: :tangle (when (eq system-type 'windows-nt) "yes")
  :END:
** MSYS2 bash
   (hm.. git bash is better)

   By default
   - explicit-shell-file-name is nil
   - explicit-bash.exe-args .. doesn't exist
   #+BEGIN_SRC emacs-lisp
(setq explicit-shell-file-name "c:/msys64/usr/bin/bash.exe")
;; so.. --login is fucking things up. like this it's perfect :D
;; also there is the --noprofile flag. not sure if I need it
(setq explicit-bash.exe-args '("--rcfile" "~/.emacs.d/dot/.bashrc" "-i"  ))
   #+END_SRC

   #+RESULTS:
   | --rcfile | ~/.emacs.d/dot/.bashrc | -i |

   #+BEGIN_SRC emacs-lisp
(defun my-on-shell-cd-error (e)
  (message "error"))

(add-hook 'shell-set-directory-error-hook  'my-on-shell-cd-error)
   #+END_SRC

   #+RESULTS:
   | --login | -i |

** COMMENT Git bash
   #+BEGIN_SRC emacs-lisp
(setq explicit-shell-file-name "c:/Program Files/Git/bin/bash.exe")
(setq explicit-bash.exe-args '("--login" "-i"))
   #+END_SRC

   #+RESULTS:
   | --login | -i |

   From https://emacs.stackexchange.com/questions/22049/git-bash-in-emacs-on-windows

** Windows bash
   #+BEGIN_SRC emacs-lisp
(defun my-bash-on-windows-shell ()
  (interactive)
  (let ((explicit-shell-file-name "C:/Windows/System32/bash.exe")
	(explicit-bash.exe-args '("--rcfile" "<(echo \"PS1='foo: '\")>" ))	
	)
    (shell)))
   #+END_SRC

   #+RESULTS:
   : my-bash-on-windows-shell

** lsp clojure fix
   #+BEGIN_SRC emacs-lisp
(setq lsp-clojure-server-command '("clojure-lsp.bat"))
   #+END_SRC

** paths: msys2
   Really useful for stuff like =ediff= etc..
   #+BEGIN_SRC emacs-lisp
(when (eq system-type 'windows-nt)
  (let (
        (mypaths
         '(
           "C:/msys64/mingw64/bin"
	   "C:/msys64/usr/local/bin"
	   "C:/msys64/usr/bin"
	   "C:/msys64/usr/bin"
	   "C:/msys64/usr/bin/site_perl"
	   "C:/msys64/usr/bin/vendor_perl"
	   "C:/msys64/usr/bin/core_perl"
           ) )
        )

    (setenv "PATH" (concat
                    (getenv "PATH")
		    ";"
		    "c:/Program Files/Chez Scheme 9.5.2/bin/ta6nt"
		    ";"
		    (mapconcat 'identity mypaths ";")
		    ))

    ;;(setq exec-path (append mypaths (list "." exec-directory)) )
    (setq exec-path (append exec-path mypaths (list exec-directory)))
    ))

   #+END_SRC

   #+RESULTS:
   | c:/Program Files/Broadcom/Broadcom 802.11 Network Adapter | C:/Python37/Scripts/ | C:/Python37/ | C:/Program Files (x86)/Common Files/Oracle/Java/javapath | C:/WINDOWS/system32 | C:/WINDOWS | C:/WINDOWS/System32/Wbem | C:/WINDOWS/System32/WindowsPowerShell/v1.0/ | C:/WINDOWS/System32/OpenSSH/ | C:/ProgramData/chocolatey/bin | c:/Program Files/Intel/WiFi/bin/ | c:/Program Files/Common Files/Intel/WirelessCommon/ | C:/Program Files/Microsoft VS Code | C:/Program Files/MiKTeX 2.9/miktex/bin/x64/ | C:/Program Files/Microsoft VS Code/bin | C:/Program Files/nodejs/ | C:/Users/actondev/AppData/Local/Android/Sdk/platform-tools/ | C:/Program Files/gnuplot/bin | C:/ProgramData/chocolatey/lib/lua53/tools | C:/Program Files/Mullvad VPN/resources | C:/tools/php74 | C:/ProgramData/ComposerSetup/bin | C:/Program Files/Git/cmd | C:/Users/actondev/.cargo/bin | C:/Users/actondev/AppData/Local/Microsoft/WindowsApps | C:/Users/actondev/bin | c:/Program Files/Intel/WiFi/bin/ | c:/Program Files/Common Files/Intel/WirelessCommon/ | C:/Users/actondev/AppData/Roaming/npm | C:/gradle/gradle-2.2/bin | C:/Users/actondev/watchman | C:/Program Files/VideoLAN/VLC | C:/Program Files/Java/jdk-11.0.5/bin | C:/Users/actondev/AppData/Roaming/Composer/vendor/bin | C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin | C:/Program Files/CMake/bin | W:/dev/_sdk/sciter/bin.win/x64 | C:/Users/actondev/bin/zig-windows-x86_64-0.6.0 | . | w:/portables/emacs-27.0.50-snapshot-2019-09-18-x86_64/libexec/emacs/27.0.50/x86_64-w64-mingw32 | C:/msys64/mingw64/bin | C:/msys64/usr/local/bin | C:/msys64/usr/bin | C:/msys64/usr/bin | C:/msys64/usr/bin/site_perl | C:/msys64/usr/bin/vendor_perl | C:/msys64/usr/bin/core_perl | w:/portables/emacs-27.0.50-snapshot-2019-09-18-x86_64/libexec/emacs/27.0.50/x86_64-w64-mingw32/ | C:/msys64/mingw64/bin | C:/msys64/usr/local/bin | C:/msys64/usr/bin | C:/msys64/usr/bin | C:/msys64/usr/bin/site_perl | C:/msys64/usr/bin/vendor_perl | C:/msys64/usr/bin/core_perl | w:/portables/emacs-27.0.50-snapshot-2019-09-18-x86_64/libexec/emacs/27.0.50/x86_64-w64-mingw32/ | C:/msys64/mingw64/bin | C:/msys64/usr/local/bin | C:/msys64/usr/bin | C:/msys64/usr/bin | C:/msys64/usr/bin/site_perl | C:/msys64/usr/bin/vendor_perl | C:/msys64/usr/bin/core_perl | w:/portables/emacs-27.0.50-snapshot-2019-09-18-x86_64/libexec/emacs/27.0.50/x86_64-w64-mingw32/ | C:/msys64/mingw64/bin | C:/msys64/usr/local/bin | C:/msys64/usr/bin | C:/msys64/usr/bin | C:/msys64/usr/bin/site_perl | C:/msys64/usr/bin/vendor_perl | C:/msys64/usr/bin/core_perl | w:/portables/emacs-27.0.50-snapshot-2019-09-18-x86_64/libexec/emacs/27.0.50/x86_64-w64-mingw32/ |

** Spellcheck (flyspell & hunspell)
   See [[https://emacs.stackexchange.com/questions/14952/how-do-i-set-up-hunspell-on-a-windows-pc][this discussion]] for details. Long story short, I was getting the following error
   #+BEGIN_SRC text
Error enabling Flyspell mode:
(Can’t find Hunspell dictionary with a .aff affix file)  
   #+END_SRC

   The problem was that upon running the following code
   #+BEGIN_EXAMPLE emacs-lisp
  '(call-process ispell-program-name
	      null-device
	      t
	      nil
	      "-D"
	      "-a"
	      null-device
	      )
   #+END_EXAMPLE
   I should get at least one line with the files =.dic= and =.aff=. But it wasn't happening (yet in ubuntu yeah)

   The solution was the following

   #+BEGIN_SRC emacs-lisp
'(setenv "DICTIONARY" "en_US")
   #+END_SRC

   Add greek dictionary

   #+BEGIN_SRC emacs-lisp
(require 'ispell)
(add-to-list 'ispell-local-dictionary-alist '("el"
                                              "[[:alpha:]]"
                                              "[^[:alpha:]]"
                                              "[']"
                                              t
                                              ("-d" "el"); Dictionary file name
                                              nil
					      ;; nil
					      utf-8
                                              ;;    iso-8859-1
					      ))

(add-to-list 'ispell-local-dictionary-alist '("el,en,es"
                                              "[[:alpha:]]"
                                              "[^[:alpha:]]"
                                              "[']"
                                              t
                                              ("-d" "el"); Dictionary file name
                                              nil
					      ;; nil
					      utf-8
                                              ;;    iso-8859-1
					      ))
   #+END_SRC

   #+RESULTS:
   | el    | [[:alpha:]] | [^[:alpha:]] | ['] | t | (-d el) | nil | utf-8      |       |
   | el    | [[:alpha:]] | [^[:alpha:]] | ['] | t | nil     | nil | nil        | utf-8 |
   | greek | [[:alpha:]] | [^[:alpha:]] | ['] | t | nil     | nil | nil        | utf-8 |
   | greek | [[:alpha:]] | [^[:alpha:]] | ['] | t | (-d el) | nil | iso-8859-1 |       |

   Multiple languages
   #+BEGIN_SRC emacs-lisp
'(setq ispell-dictionary nil)
'(setq ispell-dictionary "el,en,es")
   #+END_SRC

   #+RESULTS:
   : el,en,es

** Perfromance on windows
   [[file:w:/portables/emacs-26.3-x86_64/bin/runemacs.exe]]
   w:/portables/emacs-26.3-x86_64/bin/runemacs.exe
   
https://www.reddit.com/r/emacs/comments/bii2xl/hot_tip_for_windows_10_users/
   http://code.kliu.org/misc/elevate/
   #+BEGIN_SRC sh :tangle no
   # getting the shell executable
/bin/start cmd

echo "test" > /c/test-file
elevate2.exe 
cygstart --action=runas 

elevate.exe -k $(echo $(cygpath.exe -w -a $SHELL) --login)
elevate.exe -k -wait cmd
echo $(cygpath.exe -w -a $SHELL) --login

cygpath.exe -w -a $SHELL

fsutil.exe behavior set disable8dot3 1

fsutil.exe behavior set disableLastAccess 3

powershell -Command Add-MpPreference -ExclusionPath $(echo ~/.emacs.d)

powershell -Command Add-MpPreference -ExclusionProcess "emacs-w32.exe"

powershell -Command Add-MpPreference -ExclusionProcess "emacsclient-w32.exe"

powershell -Command Add-MpPreference -ExclusionExtension ".el"

powershell -Command Add-MpPreference -ExclusionExtension ".elc"
   #+END_SRC
** TODO COMMENT dired fix?
   Update: apparently it didn't work. it says that filed moved but.. nope!

   When renaming a file in dired (with =R=, I cannot move it in a directory that doesn't exist. See [[file:emacs-lisp/dired-fix.el]] . Fix found in a [[https://lists.gnu.org/archive/html/emacs-devel/2011-12/msg00253.html][GNU mail discussion]].
   Notes
   + =string-starts-with= doesn't exist
     replaced with =string-prefix-p=
   #+BEGIN_SRC emacs-lisp
(load-file (relative-from-init "elisp/dired-fix.el"))
   #+END_SRC

* Linux
  :PROPERTIES:
  :header-args: :tangle (when (eq system-type 'gnu/linux) "yes") :results silent
  :END:
** Open as sudo
   https://emacsredux.com/blog/2013/04/21/edit-files-as-root/
   #+BEGIN_SRC emacs-lisp
(defun er-sudo-edit (&optional arg)
  "Edit currently visited file as root.

With a prefix ARG prompt for a file to visit.
Will also prompt for a file to visit if current
buffer is not visiting a file."
  (interactive "P")
  (if (or arg (not buffer-file-name))
      (find-file (concat "/sudo:root@localhost:"
                         (read-file-name "Find file(as root): ")))
    (find-alternate-file (concat "/sudo:root@localhost:" buffer-file-name))))
   #+END_SRC

** COMMENT sudo save
   #+BEGIN_SRC emacs-lisp
(use-package sudo-save)   
   #+END_SRC

   #+RESULTS:

** COMMENT Sudo save nah
   #+BEGIN_SRC emacs-lisp :tangle no
(defun sudo-before-save-hook ()
  (set (make-local-variable 'sudo:file) (buffer-file-name))
  (when sudo:file
    (unless(file-writable-p sudo:file)
      (set (make-local-variable 'sudo:old-owner-uid) (nth 2 (file-attributes sudo:file)))
      (when (numberp sudo:old-owner-uid)
	(unless (= (user-uid) sudo:old-owner-uid)
	  (when (y-or-n-p
		 (format "File %s is owned by %s, save it with sudo? "
			 (file-name-nondirectory sudo:file)
			 (user-login-name sudo:old-owner-uid)))
	    (sudo-chown-file (int-to-string (user-uid)) (sudo-quoting sudo:file))
	    (add-hook 'after-save-hook
		      (lambda ()
			(sudo-chown-file (int-to-string sudo:old-owner-uid)
					 (sudo-quoting sudo:file))
			(if sudo-clear-password-always
			    (sudo-kill-password-timeout)))
		      nil   ;; not append
		      t	    ;; buffer local hook
		      )))))))


(add-hook 'before-save-hook 'sudo-before-save-hook)
   #+END_SRC
* COMMENT Troubleshooting etc
** checking executables
   #+BEGIN_SRC emacs-lisp
(message "do you see me?")
(executable-find "ag")
   #+END_SRC

** windows ag problem
   see https://github.com/bbatsov/helm-projectile/issues/90
   + choco uninstall ag
   + choco install ag --version 0.29.1.1641

* COMMENT notes
  #+BEGIN_SRC emacs-lisp
;; customize inital screen
(customize-group 'initialization)
  #+END_SRC
** cua mode

   #+BEGIN_SRC text
`cua--ena-cua-keys-keymap' Minor Mode Bindings:
key             binding
---             -------

C-c		Prefix Command
C-v		yank
C-x		Prefix Command
C-z		undo
ESC		Prefix Command

M-v		delete-selection-repeat-replace-region

C-c <timeout>	copy-region-as-kill

C-x <timeout>	kill-region   
   #+END_SRC
** org sh sessions example
   #+BEGIN_SRC sh :session *sh1*
echo hi
echo hi2
   #+END_SRC

   #+BEGIN_SRC sh :session *sh2*
echo "hi from sh2"
echo hi2
   #+END_SRC

   #+BEGIN_SRC sh
echo "hi from default"
   #+END_SRC
* TODO ideas to check
  + org mode : linking to certain line (can do already but, to point to the line where a function is declared?)
    https://endlessparentheses.com/use-org-mode-links-for-absolutely-anything.html
    
* COMMENT spelling notes
  :PROPERTIES:
  :header-args: :results output replace
  :END:

  listing dictionaries
  #+BEGIN_SRC sh :results output replace
hunspell -D 2>&1
  #+END_SRC

  #+RESULTS:
  #+begin_example
  SEARCH PATH:
  .;C:/msys64/mingw64/bin/;C:/msys64/mingw64/share/hunspell;C:/msys64/mingw64/share/myspell;C:/msys64/mingw64/share/myspell/dicts;C:/msys64;%USERPROFILE%/Application Data/OpenOffice.org 2/user/wordbook;C:/msys64/mingw64/share/dict/ooo;
  AVAILABLE DICTIONARIES (path is not mandatory for -d option):
  C:/msys64/mingw64/share/hunspell/el_GR
  C:/msys64/mingw64/share/hunspell/en_AG
  C:/msys64/mingw64/share/hunspell/en_AU-large
  C:/msys64/mingw64/share/hunspell/en_AU
  C:/msys64/mingw64/share/hunspell/en_BS
  C:/msys64/mingw64/share/hunspell/en_BW
  C:/msys64/mingw64/share/hunspell/en_BZ
  C:/msys64/mingw64/share/hunspell/en_CA
  C:/msys64/mingw64/share/hunspell/en_DK
  C:/msys64/mingw64/share/hunspell/en_GB
  C:/msys64/mingw64/share/hunspell/en_GH
  C:/msys64/mingw64/share/hunspell/en_HK
  C:/msys64/mingw64/share/hunspell/en_IE
  C:/msys64/mingw64/share/hunspell/en_IN
  C:/msys64/mingw64/share/hunspell/en_JM
  C:/msys64/mingw64/share/hunspell/en_NA
  C:/msys64/mingw64/share/hunspell/en_NG
  C:/msys64/mingw64/share/hunspell/en_NZ
  C:/msys64/mingw64/share/hunspell/en_PH
  C:/msys64/mingw64/share/hunspell/en_SG
  C:/msys64/mingw64/share/hunspell/en_TT
  C:/msys64/mingw64/share/hunspell/en_US-large
  C:/msys64/mingw64/share/hunspell/en_US
  C:/msys64/mingw64/share/hunspell/en_ZA
  C:/msys64/mingw64/share/hunspell/en_ZW
  #+end_example

**  <2020-04-21 Tue> aspell 
   <2020-04-21 Tue> trying aspell
   pacman -S mingw64/mingw-w64-x86_64-aspell mingw64/mingw-w64-x86_64-aspell-en mingw64/mingw-w64-x86_64-aspell-es


   #+BEGIN_SRC sh
aspell dicts
   #+END_SRC

   #+RESULTS:
   #+begin_example
   el
   en
   en-variant_0
   en-variant_1
   en-variant_2
   en-w_accents
   en-wo_accents
   en_AU
   en_AU-variant_0
   en_AU-variant_1
   en_AU-w_accents
   en_AU-wo_accents
   en_CA
   en_CA-variant_0
   en_CA-variant_1
   en_CA-w_accents
   en_CA-wo_accents
   en_GB
   en_GB-ise
   en_GB-ise-w_accents
   en_GB-ise-wo_accents
   en_GB-ize
   en_GB-ize-w_accents
   en_GB-ize-wo_accents
   en_GB-variant_0
   en_GB-variant_1
   en_GB-w_accents
   en_GB-wo_accents
   en_US
   en_US-variant_0
   en_US-variant_1
   en_US-w_accents
   en_US-wo_accents
   es
   gr
   #+end_example

   #+BEGIN_SRC sh :results replace pp
echo dont | aspell -a
echo habia | aspell -l es -a
echo "γεια" | aspell -a -l el
   #+END_SRC

   #+RESULTS:

** Installing greek
   - from https://ftp.gnu.org/gnu/aspell/dict/0index.html get the greek
   - extract
   - (now with msys2 terminal)
   - cd into the extracted
   - edit the makefil
     - add quotes around all the "cd" instructions
   - ./configure
   - make
   - make install
   - =aspell dicts= now should list greek
